<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category    design
 * @package     base_default
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php //if (!Mage::helper('core/cookie')->isUserNotAllowSaveCookie()): ?>
<?php $accountId = Mage::getStoreConfig(SOAP_ShoppingAnalytics_Helper_Data::XML_PATH_SHOPPING_ACCOUNT) ?>

<!-- BEGIN SHOPPING ROI CODE -->
<script type="text/javascript">
//<![CDATA[
    var _roi = _roi || [];
    <?php echo $this->_getOrdersTrackingCode($accountId) ?>
//]]>
</script>
<script type="text/javascript" src="https://stat.dealtime.com/ROI/ROI2.js"></script>
<!-- END SHOPPING ROI CODE -->

<?php echo $this->_addGoogleTrackingCode() ?>

<?php //endif; ?>
