<?php
/**
 * Plumrocket Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End-user License Agreement
 * that is available through the world-wide-web at this URL:
 * http://wiki.plumrocket.net/wiki/EULA
 * If you are unable to obtain it through the world-wide-web, please
 * send an email to support@plumrocket.com so we can send you a copy immediately.
 *
 * @package     Plumrocket_One_Step_Checkout
 * @copyright   Copyright (c) 2015 Plumrocket Inc. (http://www.plumrocket.com)
 * @license     http://wiki.plumrocket.net/wiki/EULA  End-user License Agreement
 */
?>

<form action="" id="co-shipping-form">
    <ul class="form-list">
        <li class="control">
            <input type="checkbox" name="shipping[same_as_billing]" id="shipping:same_as_billing" value="1" checked="checked" title="<?php echo $this->__('My billing and shipping address are the same') ?>" onclick="shipping.setSameAsBilling(this.checked)" class="checkbox" /><label for="shipping:same_as_billing"><?php echo $this->__('My billing and shipping address are the same') ?></label>
        </li>
    <?php if ($this->customerHasAddresses()): ?>
       <li class="wide" id="shipping-address-select-block">
           <label for="shipping-address-select"><?php echo $this->__('Select a shipping address from your address book or enter a new address.') ?></label>
           <div class="input-box">
               <?php echo $this->getAddressesHtmlSelect('shipping') ?>
           </div>
       </li>
    <?php endif ?>
        <li id="shipping-new-address-form"<?php if ($this->customerHasAddresses()): ?> style="display:none;"<?php endif ?>>
            <fieldset>
                <input type="hidden" name="shipping[address_id]" value="<?php echo $this->getAddress()->getId() ?>" id="shipping:address_id" />
                <ul>
                    <li class="fields"><?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getAddress())->setFieldIdFormat('shipping:%s')->setFieldNameFormat('shipping[%s]')->setFieldParams('onchange="shipping.setSameAsBilling(false)"')->toHtml() ?>
                    </li>
                    <?php if ( $this->helper('onestepcheckout')->getConfigAddressFieldEnable('company') ) { ?>
                    <li class="fields">
                        <div class="fields">
                            <label for="shipping:company"<?php echo ($this->helper('onestepcheckout')->getConfigAddressFieldRequired('company'))? ' class="required"' : ''; ?>>
                                <?php echo ($this->helper('onestepcheckout')->getConfigAddressFieldRequired('company'))? '<em>*</em>' : ''; ?>
                                <?php echo $this->__('Company') ?>
                            </label>
                            <div class="input-box">
                                <input type="text" id="shipping:company" name="shipping[company]" value="<?php echo $this->escapeHtml($this->getAddress()->getCompany()) ?>" title="<?php echo $this->__('Company') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('company') ?><?php echo ($this->helper('onestepcheckout')->getConfigAddressFieldRequired('company'))? ' required-entry' : ''; ?>" onchange="shipping.setSameAsBilling(false);" />
                            </div>
                        </div>
                    </li>
                    <?php } ?>
            <?php $_streetValidationClass = $this->helper('customer/address')->getAttributeValidationClass('street'); ?>
                    <li class="wide">
                        <label for="shipping:street1" class="required"><em>*</em><?php echo $this->__('Address') ?></label>
                        <div class="input-box">
                            <input type="text" title="<?php echo $this->__('Street Address') ?>" name="shipping[street][]" id="shipping:street1" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet(1)) ?>" class="input-text <?php echo $_streetValidationClass ?> needUpdate" onchange="shipping.setSameAsBilling(false);" />
                        </div>
                    </li>
            <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
            <?php for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>
                    <li class="wide">
                        <div class="input-box">
                            <input type="text" title="<?php echo $this->__('Street Address %s', $_i) ?>" name="shipping[street][]" id="shipping:street<?php echo $_i ?>" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet($_i)) ?>" class="input-text <?php echo $_streetValidationClass ?>" onchange="shipping.setSameAsBilling(false);" />
                        </div>
                    </li>
            <?php endfor; ?>
                    <?php if ($this->helper('customer/address')->isVatAttributeVisible()) : ?>
                    <li class="wide">
                        <label for="billing:vat_id"><?php echo $this->__('VAT Number'); ?></label>
                        <div class="input-box">
                            <input type="text" id="shipping:vat_id" name="shipping[vat_id]" value="<?php echo $this->escapeHtml($this->getAddress()->getVatId()); ?>" title="<?php echo $this->__('VAT Number'); ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('vat_id') ?>" />
                        </div>
                    </li>
                    <?php endif; ?>
                    <li class="fields">
                        <div class="field">
                            <label for="shipping:city" class="required"><em>*</em><?php echo $this->__('City') ?></label>
                            <div class="input-box">
                                <input type="text" title="<?php echo $this->__('City') ?>" name="shipping[city]" value="<?php echo $this->escapeHtml($this->getAddress()->getCity()) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('city') ?> needUpdate" id="shipping:city" onchange="shipping.setSameAsBilling(false);" />
                            </div>
                        </div>
                        <div class="field">
                            <label for="shipping:region_id" class="required"><em>*</em><?php echo $this->__('State/Province') ?></label>
                            <div class="input-box">
                                <select id="shipping:region_id" name="shipping[region_id]" title="<?php echo $this->__('State/Province') ?>" class="validate-select needUpdate" style="display:none;">
                                    <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                                </select>
                                <script type="text/javascript">
                                //<![CDATA[
                                    $('shipping:region_id').setAttribute('defaultValue',  "<?php echo $this->getAddress()->getRegionId() ?>");
                                //]]>
                                </script>
                                <input type="text" id="shipping:region" name="shipping[region]" value="<?php echo $this->escapeHtml($this->getAddress()->getRegion()) ?>" title="<?php echo $this->__('State/Province') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('region') ?> needUpdate" style="display:none;" />
                            </div>
                        </div>
                    </li>
                    <li class="fields">
                        <div class="field">
                            <label for="shipping:postcode" class="required"><em>*</em><?php echo $this->__('Zip/Postal Code') ?></label>
                            <div class="input-box">
                                <input type="text" title="<?php echo $this->__('Zip/Postal Code') ?>" name="shipping[postcode]" id="shipping:postcode" value="<?php echo $this->escapeHtml($this->getAddress()->getPostcode()) ?>" class="input-text validate-zip-international <?php echo $this->helper('customer/address')->getAttributeValidationClass('postcode') ?> needUpdate" onchange="shipping.setSameAsBilling(false);" />
                            </div>
                        </div>
                        <div class="field">
                            <label for="shipping:country_id" class="required"><em>*</em><?php echo $this->__('Country') ?></label>
                            <div class="input-box">
                                <?php echo $this->getCountryHtmlSelect('shipping') ?>
                            </div>
                        </div>
                    </li>
                    <?php if ( $this->helper('onestepcheckout')->getConfigAddressFieldEnable('telephone') 
                                ||  $this->helper('onestepcheckout')->getConfigAddressFieldEnable('fax')
                    ) { ?>
                    <li class="fields">
                        <?php if ( $this->helper('onestepcheckout')->getConfigAddressFieldEnable('telephone') ) { ?>
                        <div class="field">
                            <label for="shipping:telephone"<?php echo ($this->helper('onestepcheckout')->getConfigAddressFieldRequired('telephone'))? ' class="required"' : ''; ?>>
                                <?php echo ($this->helper('onestepcheckout')->getConfigAddressFieldRequired('telephone'))? '<em>*</em>' : ''; ?>
                                <?php echo $this->__('Telephone') ?>
                            </label>
                            <div class="input-box">
                                <?php $_telephoneValidationClass = $this->helper('customer/address')->getAttributeValidationClass('telephone');
                                if (!$this->helper('onestepcheckout')->getConfigAddressFieldRequired('telephone')) {
                                    $_telephoneValidationClass = trim(str_replace('required-entry', '', $_telephoneValidationClass));
                                } ?>
                                <input type="text" name="shipping[telephone]" value="<?php echo $this->escapeHtml($this->getAddress()->getTelephone()) ?>" title="<?php echo $this->__('Telephone') ?>" class="input-text <?php echo $_telephoneValidationClass; ?>" id="shipping:telephone" onchange="shipping.setSameAsBilling(false);" />
                            </div>
                        </div>
                        <?php } ?>
                        <?php if ( $this->helper('onestepcheckout')->getConfigAddressFieldEnable('fax') ) { ?>
                        <div class="field">
                            <label for="shipping:fax"<?php echo ($this->helper('onestepcheckout')->getConfigAddressFieldRequired('fax'))? ' class="required"' : ''; ?>>
                                <?php echo ($this->helper('onestepcheckout')->getConfigAddressFieldRequired('fax'))? '<em>*</em>' : ''; ?>
                                <?php echo $this->__('Fax') ?>
                            </label>
                            <div class="input-box">
                                <input type="text" name="shipping[fax]" value="<?php echo $this->escapeHtml($this->getAddress()->getFax()) ?>" title="<?php echo $this->__('Fax') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('fax') ?><?php echo ($this->helper('onestepcheckout')->getConfigAddressFieldRequired('fax'))? ' required-entry' : ''; ?>" id="shipping:fax" onchange="shipping.setSameAsBilling(false);" />
                            </div>
                        </div>
                        <?php } ?>
                    </li>
                    <?php } ?>
                <?php if ($this->isCustomerLoggedIn() && $this->customerHasAddresses()):?>
                    <li class="control">
                        <input type="checkbox" name="shipping[save_in_address_book]" value="1" title="<?php echo $this->__('Save in address book') ?>" id="shipping:save_in_address_book" onchange="shipping.setSameAsBilling(false);"<?php if ($this->getAddress()->getSaveInAddressBook()):?> checked="checked"<?php endif;?> class="checkbox" /><label for="shipping:save_in_address_book"><?php echo $this->__('Save in address book') ?></label></li>
                <?php else:?>
                    <li class="no-display"><input type="hidden" name="shipping[save_in_address_book]" value="1" /></li>
                <?php endif;?>
                </ul>
            </fieldset>
        </li>
    </ul>
    <div id="shipping-text">
        <div class="shipping-text-name"></div>
        <div class="shipping-text-company"></div>
        <div class="shipping-text-street"></div>
        <div class="shipping-text-city"></div>
        <div class="shipping-text-country"></div>
        <div class="shipping-text-telephone"></div>
    </div>
</form>

<script type="text/javascript">
//<![CDATA[
    var shipping = new Shipping('co-shipping-form', '<?php echo $this->getUrl('onestepcheckout/checkout/getAddress') ?>address/');
    var shippingForm = new VarienForm('co-shipping-form');
    shippingForm.extraChildParams = ' onchange="shipping.setSameAsBilling(false);"';
    //shippingForm.setElementsRelation('shipping:country_id', 'shipping:region', '<?php echo $this->getUrl('directory/json/childRegion') ?>', '<?php echo $this->__('Select State/Province...') ?>');

    //$('shipping-address-select') && shipping.newAddress(!$('shipping-address-select').value);

    var shippingRegionUpdater = new RegionUpdater('shipping:country_id', 'shipping:region', 'shipping:region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'shipping:postcode');

    $('shipping:country_id').value = '<?php echo ( $this->getAddress()->getCountryId() ) ? $this->getAddress()->getCountryId() : $this->helper("onestepcheckout")->getConfigGetDefaultCountry();?>';
    $('shipping:country_id').addClassName('needUpdate');
    shippingRegionUpdater.update();

    pjQuery_1_10_2(function(){

        sabEl = document.getElementById('shipping:same_as_billing');
        if ( pjQuery_1_10_2(sabEl).is(':checked') ) {
            shipping.setSameAsBilling(true);
        }

        function preSaveShipping($element) 
        {
            if ( checkout.isFilledForm('#co-shipping-form') ){
                if ( !filedForms['#co-shipping-form'] || $element.hasClass('needUpdate') ) {
                    checkout.preSave(1);
                }
                filedForms['#co-shipping-form'] = true;
            } else {
                filedForms['#co-shipping-form'] = false;
            }
        }

        var shippingTimeout;
        var shippingLastUpdated;
        pjQuery_1_10_2("#co-shipping-form [name^='shipping']").on('keyup', function(){
            var $this = pjQuery_1_10_2(this);
            clearTimeout(shippingTimeout);
            shippingTimeout = setTimeout(function(){preSaveShipping($this); shippingLastUpdated = $this.val();}, 2000);
        });

        pjQuery_1_10_2("#co-shipping-form [name^='shipping']").on('change', function(){
            var $this = pjQuery_1_10_2(this);
            clearTimeout(shippingTimeout);
            if ( shippingLastUpdated != $this.val() ){
                preSaveShipping($this);
            }
            shippingLastUpdated = null;
        });

    });
//]]>
</script>
