<?php
/**
 * @var Mage_Page_Block_Html_Header $this
 */
?>

<div class="top-toolbar-container">
    <div class="top-toolbar">
        <?php echo $this->getChildHtml('store_language') ?>
        <?php echo $this->getChildHtml('top.currency') ?>
        <div class="quick-links">
            <p class="welcome-msg"><?php echo $this->getChildHtml('welcome') ?> <?php echo $this->getAdditionalHtml() ?></p>
            <?php echo $this->getChildHtml('topLinks') ?>
        </div>
    </div>
</div>
<div class="header-container">
    <div class="header">
        <div class="top-wrapper">
            <?php echo $this->getChildHtml('topSearch') ?>
            <div class="header-cart-anchor"></div>
            <div class="header-cart-wrapper">
                <?php echo $this->getChildHtml('headerCart') ?>
            </div>
        </div>
        <div class="logo-wrapper">
            <?php $logo2x = Mage::helper('argento')->getLogo2xSrc(); ?>
            <?php if ($this->getIsHomePage()):?>
            <h1 class="logo"><strong><?php echo $this->getLogoAlt() ?></strong><a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo"><img src="<?php echo $this->getLogoSrc() ?>"<?php echo $logo2x ? " srcset='{$this->getLogoSrc()} 1x, {$logo2x} 2x'" : '' ?> alt="<?php echo $this->getLogoAlt() ?>" /></a></h1>
            <?php else:?>
            <a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo"><strong><?php echo $this->getLogoAlt() ?></strong><img src="<?php echo $this->getLogoSrc() ?>"<?php echo $logo2x ? " srcset='{$this->getLogoSrc()} 1x, {$logo2x} 2x'" : '' ?> alt="<?php echo $this->getLogoAlt() ?>" /></a>
            <?php endif?>
        </div>
        <div class="mobile-togglers" id="mobile-togglers">
            <?php
                $menuId = 'nav';
                $navpro = $this->getLayout()->getBlock('navigationpro.top');
                if ($navpro && $navpro->getEnabled()) {
                    $menuId = $navpro->getHtmlId();
                }
            ?>
            <a href="javascript:void(0)" class="toggle-menu" data-menu="<?php echo $menuId ?>"><i class="fa fa-2x fa-bars"></i></a>
            <a href="javascript:void(0)" class="toggle-quick-links"><i class="fa fa-2x fa-user"></i></a>
            <a href="javascript:void(0)" class="toggle-search" data-el=""><i class="fa fa-2x fa-search"></i></a>
            <a href="javascript:void(0)" class="toggle-cart"><i class="fa fa-2x fa-shopping-cart"></i></a>
        </div>
    </div>
    <div class="header-content">
        <?php $menu = $this->getChildHtml('topMenu') ?>
        <?php if (!empty($menu)) : ?>
            <?php echo $menu ?>
            <script type="text/javascript">
            document.observe('dom:loaded', function() {
                new MobileNavigation();
            });
            </script>
        <?php endif; ?>
    </div>
    <?php echo $this->getChildHtml('topContainer'); ?>
</div>
