<div class="header-container header-empty">
    <div class="header">
        <?php $logo2x = Mage::helper('argento')->getLogo2xSrc(); ?>
        <?php if ($this->getIsHomePage()):?>
        <h1 class="logo"><strong><?php echo $this->getLogoAlt() ?></strong><a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo"><img src="<?php echo $this->getLogoSrc() ?>"<?php echo $logo2x ? " srcset='{$this->getLogoSrc()} 1x, {$logo2x} 2x'" : '' ?> alt="<?php echo $this->getLogoAlt() ?>" /></a></h1>
        <?php else:?>
        <a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo"><strong><?php echo $this->getLogoAlt() ?></strong><img src="<?php echo $this->getLogoSrc() ?>"<?php echo $logo2x ? " srcset='{$this->getLogoSrc()} 1x, {$logo2x} 2x'" : '' ?> alt="<?php echo $this->getLogoAlt() ?>" /></a>
        <?php endif?>
    </div>
</div>
