<?php
/**
 * Plumrocket Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End-user License Agreement
 * that is available through the world-wide-web at this URL:
 * http://wiki.plumrocket.net/wiki/EULA
 * If you are unable to obtain it through the world-wide-web, please
 * send an email to support@plumrocket.com so we can send you a copy immediately.
 *
 * @package     Plumrocket_One_Step_Checkout
 * @copyright   Copyright (c) 2015 Plumrocket Inc. (http://www.plumrocket.com)
 * @license     http://wiki.plumrocket.net/wiki/EULA  End-user License Agreement
 */

/**
 * @see Mage_Checkout_Block_Cart_Totals
 */
?>

<?php if ($this->getTotals()): ?>
<tfoot>
    <?php $_colspan = $this->helper('tax')->displayCartBothPrices() ? 5 : 3; ?>
    <?php echo $this->renderTotals(null, $_colspan); ?>
    <?php echo $this->renderTotals('footer', $_colspan); ?>
    <?php if ($this->needDisplayBaseGrandtotal()):?>
    <tr>
        <td class="a-right" colspan="<?php echo $_colspan; ?>">
            <small><?php echo $this->helper('sales')->__('Your credit card will be charged for') ?></small>
        </td>
        <td class="a-right">
            <small><?php echo $this->displayBaseGrandtotal() ?></small>
        </td>
    </tr>
    <?php endif?>
</tfoot>
<?php endif; ?>
