<?php
    $livePreviewUrl = Mage::helper("adminhtml")->getUrl("*/*/preview");
    $model = Mage::registry('reminder_data');
    $entityId = $model->getEntityId();
?>
<div class="fieldset fieldset-wide" id="preview_fieldset">
    <iframe id="reminder-live" style="background-color: #FFF; width:100%; height:700px;" frameBorder="0"></iframe>
</div>

<script type="text/javascript">
    function reminderLiveUpdate(html) {
        iframeElementContainer = document.getElementById('reminder-live').contentDocument;
        iframeElementContainer.open();
        iframeElementContainer.writeln(html);
        iframeElementContainer.close();
    }
    function sendRequest() {
        var imageSrc = $('loading_mask_loader').select('img')[0].src,
            liveUrl = '<?php echo $livePreviewUrl ?>';

        $('loading_mask_loader').innerHTML = '<img src=\'' + imageSrc + '\'/><br/>' + "Generating Preview";
        var params = {
            entityId: <?php echo $entityId; ?>
        };
        new Ajax.Request(liveUrl, {
            method: 'post',
            parameters: params,
            onSuccess: showResponse
        });
    }

    function showResponse(response) {
        var response = response.responseText.evalJSON();
        if (response.completed) {
            $('loading-mask').show();
            reminderLiveUpdate(response.html);
        }
    }

    varienGlobalEvents.attachEventHandler('showTab', function(arg) {
        if (arg.tab.id == "page_tabs_preview_section") {
            sendRequest();
        }
    });
</script>