<?php
/**
 * @author         Vladimir Popov
 * @copyright      Copyright (c) 2014 Vladimir Popov
 */
// in case redirect fails
if (Mage::registry('redirect_url')) {
    ?>
    <meta http-equiv="refresh" content="0;url=<?php echo Mage::registry('redirect_url') ?>">
    <script type="text/javascript">
        window.location = '<?php echo Mage::registry('redirect_url') ?>';
    </script>
    <?php
}

// get temporary data
$tmpData = Mage::getSingleton('core/session')->getData('webform_result_tmp_' . $this->getWebform()->getId());
$tmpResult = new Varien_Object();
if (!empty($tmpData['field']) && is_array($tmpData['field'])) {
    foreach ($tmpData['field'] as $field_id => $value) {
        $tmpResult->setData('field_' . $field_id, $value);
    }
}

if ($this->getWebform()->getIsActive() == VladimirPopov_WebForms_Model_Webforms::STATUS_DISABLED || !$this->isDirectAvailable()) {
    echo $this->getNotAvailableMessage();
} else {

    if (Mage::registry('show_form_name')) {
        ?>
        <div class="page-title">
            <h1><?php echo $this->getWebform()->getName(); ?></h1>
        </div>
    <?php } ?>

    <?php if ($this->isAjax()) { ?>
        <div id="webform_<?php echo $this->getWebform()->getId() ?>_success_text" class="std webforms-success-text"
             style="display:none"></div>
         <?php } ?>

    <?php
    if (Mage::registry('show_success')) {
        ?>
        <div class="std webforms-success-text">
            <?php echo $this->getWebform()->getSuccessText() ?>
        </div>
        <?php
    } else {
        ?>

        <div id="webform_<?php echo $this->getWebform()->getId() ?>_form">

            <?php if ($this->getWebform()->getDescription()) { ?>
                <div class="std">
                    <?php echo $this->getWebform()->getDescription(); ?>
                </div>
            <?php } ?>

            <?php if ($this->isAjax()) { ?>
                <iframe id="webform_<?php echo $this->getWebform()->getId() ?>_iframe"
                        name="webform_<?php echo $this->getWebform()->getId() ?>_iframe"
                        style="width:0;height:0;border:0;position:absolute"></iframe>
                    <?php } ?>

            <form action="<?php echo $this->getFormAction() ?>" method="post"
                  name="webform_<?php echo $this->getWebform()->getId() ?>"
                  id="webform_<?php echo $this->getWebform()->getId() ?>" enctype="<?php echo $this->getEnctype() ?>"
                  class="webforms-<?php echo $this->getWebform()->getCode() ?>"
                  <?php if ($this->isAjax()) { ?>target="webform_<?php echo $this->getWebform()->getId() ?>_iframe"<?php } ?>>


                <input type="hidden" name="submitWebform_<?php echo $this->getWebform()->getId() ?>" value="1"/>
                <input type="hidden" name="webform_id" value="<?php echo $this->getWebform()->getId() ?>"/>

                <?php
                if (is_array($this->getData('hidden'))) {
                    foreach ($this->getData('hidden') as $key => $value) {
                        ?>
                        <input type="hidden" name="<?php echo $key ?>" value="<?php echo $value ?>"/>
                        <?php
                    }
                }
                ?>

                <?php
                if (count($this->getWebform()->_getHidden())) {
                    foreach ($this->getWebform()->_getHidden() as $field) {
                        echo $field->toHtml();
                    }
                }
                ?>

                <?php
                foreach ($this->getWebform()->_getFieldsToFieldsets() as $fieldset_id => $fieldset) {
                    ?>

                    <div id="fieldset_<?php echo $fieldset_id ?>" class="fieldset fieldset-<?php echo $fieldset_id ?>"
                         <?php if ($fieldset['logic_visibility'] == VladimirPopov_WebForms_Model_Logic::VISIBILITY_HIDDEN) echo 'style="display:none"'; ?>>

                        <?php if (!empty($fieldset['name'])) { ?>
                            <h2 class="legend"><?php echo $fieldset['name'] ?></h2>
                        <?php } ?>

                        <ul class="form-list">
                            <?php
                            $k = 0;
                            $j = 0;
                            $prev = false;
                            $fields_count = count($fieldset['fields']);
                            foreach ($fieldset['fields'] as $field) {

                                // set temporary value
                                $field->setData('result', $tmpResult);

                                $size_class = "fields";
                                $field_class = "field";
                                if ($field->getSize() == 'wide') {
                                    $size_class = "wide";
                                    $field_class = "";
                                }
                                ?>
                                <?php
                                if ($j % 2 == 0 || $field->getSize() == 'wide' || $prev->getSize() == 'wide') {
                                    $j = 0;
                                    ?>
                                    <?php if ($k > 1) { ?></li><?php } ?>
                                    <li <?php if ($size_class == 'wide') { ?>id="field_<?php echo $field->getId() ?>_row" <?php } ?>
                                                                             class="<?php echo $size_class ?> <?php if ($size_class == 'wide') { ?>webforms-fields-row-<?php echo $field->getId() ?><?php } ?>"
                                                                             <?php if ($size_class == 'wide' && $field->getData('logic_visibility') == VladimirPopov_WebForms_Model_Logic::VISIBILITY_HIDDEN) echo 'style="display:none"'; ?>>
                                                                             <?php } ?>
                                                                             <?php
                                                                             $field_css_type = 'type-' . str_replace('/', '-', $field->getType());
                                                                             ?>
                                    <div id="field_<?php echo $field->getId() ?>"
                                         class="<?php echo $field_class ?> <?php echo $field_css_type ?> webforms-fields-<?php echo $field->getId() ?><?php if ($field->getCode()) { ?> webforms-fields-<?php
                                             echo $field->getCode();
                                         }
                                         ?>"
                                         <?php if ($field->getData('logic_visibility') == VladimirPopov_WebForms_Model_Logic::VISIBILITY_HIDDEN) echo 'style="display:none"'; ?>>

                                        <?php if ($field->getType() != 'html' && $field->getType() != 'subscribe') { ?>
                                            <label id="label_field<?php echo $field->getId() ?>" for="field<?php echo $field->getId() ?>"
                                                   <?php if ($field->getRequired()) { ?>class="required"<?php } ?>>
                                                   <?php if ($field->getRequired()) { ?>
                                                    <em>*</em>
                                                <?php } ?>
                                                <?php echo $field->getName() ?>
                                                <?php
                                                $tooltip = $field->getTooltip();
                                                if ($tooltip) {
                                                    echo $this->getLayout()->createBlock(
                                                            'core/template', 'field' . $field->getId() . '_tooltip', array(
                                                        'field' => $field,
                                                        'tooltip' => $tooltip,
                                                        'template' => 'webforms/scripts/tooltip.phtml',
                                                            )
                                                    )->toHtml();
                                                }
                                                ?>
                                            </label>
                                        <?php } ?>

                                        <div class="input-box">
                                            <?php echo $field->toHtml(); ?>

                                            <?php if ($field->getComment()) { ?>
                                                <p class="webforms-fields-comment">
                                                    <?php echo nl2br($field->getComment()) ?>
                                                </p>
                                            <?php } ?>

                                            <?php if ($field->getValidationAdvice()) { ?>
                                                <div style="display:none" class="validation-advice" id="advice-required-entry-field<?php echo $field->getId() ?>">
                                                    <?php echo $field->getValidationAdvice() ?>
                                                </div>
                                            <?php } ?>
                                        </div>

                                    </div>
                                    <?php if ($k == $fields_count - 1) { ?>
                                    </li>
                                <?php } ?>
                                <?php
                                $k++;
                                $j++;
                                $prev = $field;
                            }
                            ?>
                        </ul>

                    </div>

                    <?php
                } // foreach 'fields_to_fieldsets'
                ?>

                <?php if (Mage::registry('use_captcha')) { ?>
                    <div class="fieldset">
                        <h2 class="legend">Captcha</h2>
                        <ul class="form-list">
                            <li class="fields">
                                <div class="field">
                                    <?php echo $this->getCaptcha()->getHTML() ?>
                                </div>
                            </li>
                        </ul>
                    </div>
                <?php } ?>

                <?php
                session_start();
                $form_id = $this->getWebform()->getId();
                $digit1 = mt_rand(1, 20);
                $digit2 = mt_rand(1, 20);
                if (mt_rand(0, 1) === 1) {
                    $math = "$digit1 + $digit2";
                    $_SESSION['captcha_fgc_' . $form_id] = $digit1 + $digit2;
                } else {
                    //$math = "$digit1 - $digit2";
                    //$_SESSION['captcha_fgc_' . $form_id] = $digit1 - $digit2;
                    $math = "$digit1 + $digit2";
                    $_SESSION['captcha_fgc_' . $form_id] = $digit1 + $digit2;
                }
                if ($form_id == 8 || $form_id == 6 || $form_id == 5 || $form_id == 3) {
                    if ($form_id == 5 || $form_id == 3) {
                        $field_form5 = 'captcha_form5';
                    }else{
                        $field_form5 = 'captcha_form'.$form_id;
                    }
                    ?>
                    <div class="fieldset <?php echo $field_form5; ?>">
                        <label class="required"><em>*</em>Captcha</label>
                        <div class="input-box">
                            <ul class="form-list">
                                <li class="fields">
                                    <div class="field">
                                        <span class="tvmath"><?php echo $math; ?></span> = <input name="captcha_fgc_<?php echo $form_id ?>" id="tv_captcha_<?php echo $form_id ?>" type="text" class="tv_captcha input-text tv_captcha_<?php echo $form_id ?>"/>
                                        <input type="hidden" name="answer_form_<?php echo $form_id ?>" value="<?php echo $_SESSION['captcha_fgc_' . $form_id] ?>" class="tv_captcha_answer_<?php echo $form_id ?>"/>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </div>  
                <?php } ?>        

                <?php
                if (Mage::getStoreConfig('webforms/honeypot/enable')) {
                    echo $this->getLayout()->createBlock(
                            'core/template', 'webform_' . $this->getWebform()->getId() . '_honeypot', array(
                        'webform' => $this->getWebform(),
                        'template' => 'webforms/scripts/honeypot.phtml',
                            )
                    )->toHtml();
                }
                ?>

                <div class="buttons-set">
                    <p class="required"><?php echo $this->__('* Required Fields') ?></p>
                    <button type="button" class="button"
                            id="webform_<?php echo $this->getWebform()->getId() ?>_submit_button"
                            onclick="webform_<?php echo $this->getWebform()->getId() ?>_submit()"
                            title="<?php echo $this->__('submit') ?>">
                        <span>
                            <span><?php echo $this->__($this->getWebform()->getSubmitButtonText()) ?></span>
                        </span>
                    </button>
                    <span class="please-wait" id="webform_<?php echo $this->getWebform()->getId() ?>_sending_data"
                          style="display:none;">
                        <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>"
                             alt="<?php echo $this->__('Sending...') ?>" title="<?php echo $this->__('Sending...') ?>"
                             class="v-middle"/><span
                             id="webform_<?php echo $this->getWebform()->getId() ?>_progress_text"><?php echo $this->__('Sending...') ?></span>
                    </span>
                </div>
                <?php
                if ($currentproduct = Mage::registry('current_product')) {
                    $product_name = $currentproduct->getName();
                    $product_link = $currentproduct->getUrl();
                    ?>
                    <input type="hidden" name="product_name" value="<?php echo $product_name ?>" />
                    <input type="hidden" name="product_link" value="<?php echo $product_link ?>" />
                    <?php
                }
                ?>
                    
                <?php
                if ($currentcategory = Mage::registry('current_category')) {
                    $category_name = $currentcategory->getName();
                    $category_link = $currentcategory->getUrl();
                    ?>
                    <input type="hidden" name="category_name" value="<?php echo $category_name ?>" />
                    <input type="hidden" name="category_link" value="<?php echo $category_link ?>" />
                    <?php
                }
                ?>
            </form>

        </div>

        <?php
        echo $this->getLayout()->createBlock(
                'core/template', 'webform_' . $this->getWebform()->getId() . '_submit_script', array(
            'webform' => $this->getWebform(),
            'ajax' => $this->isAjax(),
            'template' => 'webforms/scripts/submit.phtml',
            'scroll_to' => $this->getData('scroll_to'),
                )
        )->toHtml();
        ?>

        <?php
        echo $this->getLayout()->createBlock(
                'core/template', 'webform_' . $this->getWebform()->getId() . '_logic', array(
            'webform' => $this->getWebform(),
            'template' => 'webforms/scripts/logic.phtml',
                )
        )->toHtml();
        ?>

        <?php
    } // if(show_success)
} // is active
if ($form_id == 8 || $form_id == 6 || $form_id == 5 || $form_id == 3) {
    ?>

    <script type="text/javascript">

        Validation.add('tv_captcha_<?php echo $form_id ?>', 'Please make sure your password match.', function (v) {
            var tv_captcha = $$('.tv_captcha_<?php echo $form_id ?>')[0];
            var tv_captcha_answer = $$('.tv_captcha_answer_<?php echo $form_id ?>')[0];
            console.log(tv_captcha.value == tv_captcha_answer.value);
            return(tv_captcha.value == tv_captcha_answer.value)
        });
        Validation.add('tvinternal_phone_<?php echo $form_id ?>', 'Phone number invalid, only numbers, spaces and hyphens can be used.', function (v) {
            var tvinternal_phone = $$('.tvinternal_phone_<?php echo $form_id ?>')[0];
            var tvphonevalue = tvinternal_phone.value;
            //console.log(tvphonevalue.length, tvinternal_phone.value, jQuery('.tvinternal_phone_6').val());
            if (parseInt(jQuery.trim(jQuery('.tvinternal_phone_<?php echo $form_id ?>').val()).length) > 6) {
                console.log(tvphonevalue.length, 'true');
            } else {
                console.log(tvphonevalue.length, 'false');
                alert('Phone number invalid, only numbers, spaces and hyphens can be used.');
            }
            return jQuery.trim(jQuery('.tvinternal_phone_<?php echo $form_id ?>').val()).length > 6;
        });
    </script>
    <?php
}
?>