<?php
/**
 * Plumrocket Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End-user License Agreement
 * that is available through the world-wide-web at this URL:
 * http://wiki.plumrocket.net/wiki/EULA
 * If you are unable to obtain it through the world-wide-web, please 
 * send an email to support@plumrocket.com so we can send you a copy immediately.
 *
 * @package     Plumrocket_Search
 * @copyright   Copyright (c) 2015 Plumrocket Inc. (http://www.plumrocket.com)
 * @license     http://wiki.plumrocket.net/wiki/EULA  End-user License Agreement
 */


$helper = $this->helper('psearch');
$config = $this->helper('psearch/config');
$catalogSearchHelper =  $this->helper('catalogsearch');
?>

<script type="text/javascript">
	pjQuery_1_10_2(document).ready(function() {
		var psearch = new Plumrocket_Search({
			path: 			'<?php echo $this->jsQuoteEscape($this->getUrl("psearch", array("_secure" => Mage::app()->getStore()->isCurrentlySecure()) )); ?>',
			delay: 			<?php echo abs($config->getQueryDelay()); ?>,
			queryLenghtMin: <?php echo $config->getSearchMinLenght(); ?>
		});

		psearch.run();
	});
</script>

<form id="pas-mini-form" action="<?php echo $catalogSearchHelper->getResultUrl() ?>" method="get">
    <div class="pas-form-search">
    	<?php if($config->enabledFilterCategories() && $categoryTree = $helper->getCategoryTree()) : ?>
		<div class="pas-nav-left">
			<div class="pas-search-facade">
				<span class="pas-search-label">
					<?php echo $this->escapeHtml(str_replace('&nbsp;', '', isset($categoryTree[$helper->getQueryCategory()])? $categoryTree[$helper->getQueryCategory()] : $categoryTree[0])); ?>
				</span>
				<i class="pas-search-icon"></i>
			</div>
			<select name="cat" class="pas-search-dropdown">
			<?php foreach ($categoryTree as $value => $label) : ?>
				<option value="<?php echo $this->escapeHtml($value); ?>" <?php echo $value == $helper->getQueryCategory()? 'selected' : ''; ?>><?php echo $this->escapeHtml($label); ?></option>
			<?php endforeach; ?>
			</select>
		</div>
		<?php endif; ?>

        <div class="pas-nav-right">
        	<button type="submit" title="<?php echo $this->__('Search') ?>" class="pas-button"><span><span><?php echo $this->__('Search') ?></span></span></button>
        </div>

		<div class="pas-nav-center">
			<div class="pas-search-field">
        		<input id="pas-input" type="text" name="<?php echo $catalogSearchHelper->getQueryParamName() ?>" value="<?php echo $catalogSearchHelper->getEscapedQueryText() ?>" class="pas-input-text" maxlength="<?php echo $catalogSearchHelper->getMaxQueryLength();?>" autocomplete="off" tabindex="1" />
        		<img src="<?php echo $this->getSkinUrl('images/plumrocket/psearch/psearch-loader.gif');?>" width="22"  alt="loader" class="pas-loader" />
        	</div>
        </div>

        <div id="pas-tooltip"></div>

    </div>
</form>
