<?php
    $slideshowGroupId = uniqid('slideshowGroup_image_');
    $title = $this->getData('title');
    $path  = $this->getData('path');
    list($_thumbnailWidth, $_thumbnailHeight) = explode('x', Mage::getStoreConfig('lightboxpro/size/thumbnail'));
    $thumbnailWidth = $this->getData('thumbnailwidth');
    $thumbnailHeight = $this->getData('thumbnailheight');
    if (!empty($thumbnailWidth)) {
        $_thumbnailWidth = $thumbnailWidth;
    }
    if (!empty($thumbnailHeight)) {
        $_thumbnailHeight = $thumbnailHeight;
    }
?>

<script type="text/javascript">
    // gallery config object
    hscustomConfigs<?php echo $slideshowGroupId?> = {
        slideshowGroup: '<?php echo $slideshowGroupId?>'
    };
</script>
<a href="<?php echo Mage::helper('lightboxpro/image')->setImage($path); ?>" class="highslide" onclick="return hs.expand(this, hscustomConfigs<?php echo $slideshowGroupId?>)" title="<?php echo $title?>">
    <img src="<?php echo Mage::helper('lightboxpro/image')->setImage($path)->resize($_thumbnailWidth, $_thumbnailHeight); ?>"  alt="<?php echo $title?>" style="width: <?php echo $_thumbnailWidth;?>;height:<?php echo $_thumbnailHeight?>;"/>
</a>