<?php
$_helper = $this->helper('catalog/output');
$productCollection  = $this->getData('collection');
$count              = $productCollection ? $productCollection->count() : 0;
$carousel           = $this->getData('carousel');
$row                = $this->getData('row');
$column             = $carousel == 1 && $row == 1 ? $count : ($carousel == 1 && $row > 1 ? $row : $this->getData('column'));
/* @var $helper Mage_Catalog_Helper_Image */
$helper             = Mage::helper('catalog/image');
?>
<?php if (!$count): ?>
    <p class="note-msg">
        <?php echo $this->__('There are no products matching the selection.') ?>
    </p>
<?php else: ?>
    <?php $i=0; foreach ($productCollection as $_product): ?>
        <?php /* @var $_product Mage_Catalog_Model_Product */ ?>
        <?php if ($carousel == 1 && $row > 1 && $i == 0): ?>
            <div class="owl-carousel">
        <?php endif ?>
        <?php if ($i % $column == 0 || ($row > 1 && $i % $row == 0)): ?>
        <ul class="products-grid <?php echo $carousel && $row == 1 ? ' owl-carousel' : '' ?>">
    <?php endif ?>
        <?php $i++ ?>
        <li class="item">
            <div class="product-content">
                <div class="row show-grid">
                    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(340); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>

                        <div class="wrapper-product-date">
                            <?php $currentDate = Mage::getModel('core/date')->date('M d, Y h:i', strtotime($_product->getData('special_to_date')));?>
                            <div class="product-date clearfix" data-date="<?php echo $currentDate ?>"></div>
                        </div>
                    </div>
                    <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
                        <!-- // Product Descriptions -->
                        <div class="product-shop">
                            <div class="f-fix">
                                <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                                <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?></a></h2>

                                <div class="product-price">
                                    <?php if ($_product->getRatingSummary()): ?>
                                        <?php echo $this->getReviewsSummaryHtml($_product) ?>
                                    <?php endif; ?>
                                    <?php echo $this->getPriceHtml($_product, true) ?>
                                </div>
                                <div class="desc std">
                                    <?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                    <a href="<?php echo $_product->getProductUrl() ?>"
                                       title="<?php echo $_productNameStripped ?>"
                                       class="link-learn"><?php echo $this->__('Learn More') ?></a>
                                </div>
                                <div class="product-watches-color">
                                    <?php
                                    // Provides extra blocks on which to hang some features for products in the list
                                    // Features providing UI elements targeting this block will display directly below the product name
                                    if ($this->getChild('name.after')) {
                                        $_nameAfterChildren = $this->getChild('name.after')->getSortedChildren();
                                        foreach ($_nameAfterChildren as $_nameAfterChildName) {
                                            $_nameAfterChild = $this->getChild('name.after')->getChild($_nameAfterChildName);
                                            $_nameAfterChild->setProduct($_product);
                                            echo $_nameAfterChild->toHtml();
                                        }
                                    }
                                    ?>
                                </div>
                                <div class="actions">
                                    <?php if ($_product->isSaleable()): ?>
                                        <div class="action-list addtocart">
                                            <button type="button" title="<?php echo $this->__('Add to Cart') ?>"
                                                    class="btn-cart"
                                                    onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')">
                                                <span><span><i class="fa fa-shopping-cart"></i></span></span>
                                            </button>
                                        </div>
                                    <?php else: ?>
                                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                                    <?php endif; ?>
                                    <div class="action-list">
                                        <ul class="add-to-links">
                                            <?php if ($_compareUrl = $this->getAddToCompareUrl($_product)): ?>
                                                <li><a href="<?php echo $_compareUrl ?>" class="link-compare <?php echo $classSimple; ?>"  data-toggle="tooltip" data-placement="left" title="<?php echo $this->__('Compare');?>"><i class="fa fa-pie-chart"></i></a></li>
                                            <?php endif; ?>
                                        </ul>
                                    </div>
                                    <div class="action-list">
                                        <ul class="add-to-links">
                                            <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                                <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist <?php echo $classSimple; ?>"  data-toggle="tooltip" data-placement="left" title="<?php echo $this->__('Wishlist');?>"><i class="fa fa-heart"></i></a></li>
                                            <?php endif; ?>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- // End Product Descriptions -->
                    </div>
                </div>
            </div>
        </li>
        <?php if ($i == $count || $i % $column == 0 || ($row > 1 && $i % $row == 0)): ?>
        </ul>
    <?php endif ?>
        <?php if ($carousel == 1 && $row > 1 && $i == $count): ?>
            </div>
        <?php endif ?>
    <?php endforeach ?>
<?php endif ?>
