<?php
/*
  Created on : Jul 24, 2015, 3:03:33 PM
  Author     : Tran Trong Thang
  Email      : trantrongthang1207@gmail.com
 */

/*
 * Thuc hien load toan bo cac ban ghi
 */
$id = $this->getRequest()->getParam('id');
$item = Mage::getModel('articles/articles')->load($id);


?>
<form class="" method="POST" action="articles/save">
    <h1>
        <a href="<?php echo $this->getUrl('articles/index/view/id/' . $item->getId()); ?>">
            <?php
            echo $item->getData('title');
            ?>
        </a>
    </h1>
    <div>
        <?php
        echo $item->getData('short_desc');
        ?>
    </div>
    <div>
        <?php
        echo $item->getData('long_desc');
        ?>
    </div>
    <div>
        <?php
        echo $item->getData('status');
        ?>
    </div>
    <div>
        <?php
        echo $item->getData('created_time');
        ?>
    </div>
    <div>
        <?php
        echo $item->getData('update_time');
        ?>
    </div>
</form>
