<?php
/**
 * Plumrocket Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End-user License Agreement
 * that is available through the world-wide-web at this URL:
 * http://wiki.plumrocket.net/wiki/EULA
 * If you are unable to obtain it through the world-wide-web, please
 * send an email to support@plumrocket.com so we can send you a copy immediately.
 *
 * @package     Plumrocket_One_Step_Checkout
 * @copyright   Copyright (c) 2015 Plumrocket Inc. (http://www.plumrocket.com)
 * @license     http://wiki.plumrocket.net/wiki/EULA  End-user License Agreement
 */
?>

<?php /** @var $this Mage_Checkout_Block_Onepage_Shipping_Method_Available */ ?>
<?php $_shippingRateGroups = $this->getShippingRates(); ?>
<?php if (!$_shippingRateGroups): ?>
    <p>
        <?php echo $this->__('Sorry, no quotes are available for this order at this time.') ?>
        <?php echo $this->__('Please fill all required address fields, or indicate other address.') ?>
    </p>
<?php else: ?>
    <dl class="sp-methods">
        <?php $shippingCodePrice = array(); ?>
        <?php $_sole = count($_shippingRateGroups) == 1;
        foreach ($_shippingRateGroups as $code => $_rates): ?>
            <dt><?php echo $this->escapeHtml($this->getCarrierName($code)) ?></dt>
            <dd>
                <ul>
                    <?php $_sole = $_sole && count($_rates) == 1;
                    foreach ($_rates as $_rate): ?>
                            <?php $shippingCodePrice[] = "'" . $_rate->getCode() . "':" . (float) $_rate->getPrice(); ?>
                        <li>
                            <?php if ($_rate->getErrorMessage()): ?>
                                <ul class="messages"><li class="error-msg"><ul><li><?php echo $this->escapeHtml($_rate->getErrorMessage()) ?></li></ul></li></ul>
                            <?php else: ?>
                                <?php if ($_sole) : ?>
                                    <span class="no-display"><input name="shipping_method" type="radio" value="<?php echo $_rate->getCode() ?>" id="s_method_<?php echo $_rate->getCode() ?>" checked="checked" /></span>
                                <?php else: ?>
                                    <input name="shipping_method" type="radio" value="<?php echo $_rate->getCode() ?>" id="s_method_<?php echo $_rate->getCode() ?>"<?php if ($_rate->getCode() === $this->getAddressShippingMethod()) echo ' checked="checked"' ?> class="radio"/>

                    <?php if ($_rate->getCode() === $this->getAddressShippingMethod()): ?>
                                        <script type="text/javascript">
                                            //<![CDATA[
                                            lastPrice = <?php echo (float) $_rate->getPrice(); ?>;
                                            //]]>
                                        </script>
                                    <?php endif; ?>

                                    <?php endif; ?>
                                <label for="s_method_<?php echo $_rate->getCode() ?>"<?php if ($_rate->getCode() === $this->getAddressShippingMethod() || $_sole) echo ' class="active"'; ?>><?php echo $this->escapeHtml($_rate->getMethodTitle()) ?>
                                    <?php $_excl = $this->getShippingPrice($_rate->getPrice(), $this->helper('tax')->displayShippingPriceIncludingTax()); ?>
                                    <?php $_incl = $this->getShippingPrice($_rate->getPrice(), true); ?>
                                    <?php echo $_excl; ?>
                                    <?php if ($this->helper('tax')->displayShippingBothPrices() && $_incl != $_excl): ?>
                                        (<?php echo $this->__('Incl. Tax'); ?> <?php echo $_incl; ?>)
                                <?php endif; ?>
                                </label>
                        <?php endif ?>
                        </li>
            <?php endforeach; ?>
                </ul>
            </dd>
    <?php endforeach; ?>
    </dl>
    <script type="text/javascript">
    //<![CDATA[
    <?php if (!empty($shippingCodePrice)): ?>
            var shippingCodePrice = {<?php echo implode(',', $shippingCodePrice); ?>};
    <?php endif; ?>

        $$('input[type="radio"][name="shipping_method"]').each(function (el) {
            Event.observe(el, 'click', function () {
                if (el.checked == true) {

                    $$('label[for^="s_method"].active').each(function (label) {
                        label.removeClassName('active');
                    });
                    var $label = $$('label[for="' + el.identify() + '"]');
                    $label[0].addClassName('active');

                    var getShippingCode = el.getValue();
    <?php if (!empty($shippingCodePrice)): ?>
                        var newPrice = shippingCodePrice[getShippingCode];
                        if (!lastPrice) {
                            lastPrice = newPrice;
                            quoteBaseGrandTotal += newPrice;
                        }
                        if (newPrice != lastPrice) {
                            quoteBaseGrandTotal += (newPrice - lastPrice);
                            lastPrice = newPrice;
                        }
    <?php endif; ?>
                    checkQuoteBaseGrandTotal = quoteBaseGrandTotal;

                    checkout.preSave(2);
                    return false;
                }
            });
        });

        pjQuery_1_10_2(function () {
    <?php if ($_sole) { ?>
                pjQuery_1_10_2('#co-shipping-method-form input.radio').first().click();
    <?php } elseif ($configDefaultShippingMethod = $this->helper("onestepcheckout")->getConfigGetDefaultShippingMethod()) { ?>
                if (!pjQuery_1_10_2('#co-shipping-method-form input.radio:checked').length) {
                    pjQuery_1_10_2('#co-shipping-method-form input[id^="s_method_<?php echo $configDefaultShippingMethod; ?>"]').first().click();
                }
    <?php } ?>
        });
    //]]>
    </script>
<?php endif; ?>