<?php
if (Mage::helper('richsnippets')->snippetsEnabled()) {
    $snippetsType = Mage::getStoreConfig('richsnippets/general/snippetsType');
    $websiteParameters = array(
        'sitename'        => Mage::getStoreConfig('richsnippets/website/sitename'),
        'siteurl'         => Mage::getStoreConfig('richsnippets/website/siteurl')
    );

    ?>
        <!-- JSON Format -->
        <?php  if ($snippetsType == '0') { ?>
            <script type="application/ld+json">
                {
                    "@context": "http://schema.org",
                    "@type": "WebSite",
                    "url": "<?php echo $websiteParameters['siteurl'] ?>",
                    "name": "<?php echo $websiteParameters['sitename'] ?>",
                    "potentialAction": {
                        "@type": "SearchAction",
                        "target": "<?php echo $this->helper('catalogsearch')->getResultUrl()?>?q={search_term_string}",
                        "query-input": "required name=search_term_string"
                    }
                }
            </script>
        <?php } ?>

        <!-- Microdata -->
        <?php if ($snippetsType == '1') { ?>
            <div itemscope itemtype="http://schema.org/WebSite">
                <meta itemprop="url" content="<?php echo $websiteParameters['siteurl'] ?>"/>
                <meta itemprop="name" content="<?php echo $websiteParameters['sitename'] ?>"/>
            </div>
        <?php } ?>
<?php } ?>