<?php
/*
  Created on : Jul 4, 2015, 10:19:41 AM
  Author     : Tran Trong Thang
  Email      : trantrongthang1207@gmail.com
 */
echo Mage::getStoreConfig('webforms/proccessresult/enable');
?>
<div id="tv_home_free" class="item-slider item1"><div class="content"><p class="first-content">free design assistance</p><p class="second-content">visual mock ups / Pre production samples</p></div></div>
<script type="text/javascript">
    jQuery.noConflict();
    jQuery(function ($) {


        $('#tv_home_free').fancybox({
            'wrapCSS': 'tvwrapcss',
            'href': 'http://localhost/magento/magento/webformpopup/index/webform/id/2',
            'type': 'ajax',
            'autoSize': true,
            'titleShow': false,
            'autoScale': false,
            'transitionIn': 'none',
            'transitionOut': 'none',
            'scrolling': 'auto',
            'padding': 0,
            'margin': 0,
            'centerOnScroll': true,
            'height': 'auto',
            'afterShow': function () {
//                $(".tvinternal_phone").mask('000000000000', {
//                    translation: {
//                        '0': {
//                            pattern: /[\ \-\0-9]/, optional: true
//                        }
//                    }
//                });
            },
            'helpers': {
                overlay: {
                    locked: false // try changing to true and scrolling around the page
                }
            }
        });

        $('#tv_home_best').fancybox({
            'wrapCSS': 'tvwrapcss',
            'href': 'webformpopup/index/webform/id/13',
            'type': 'ajax',
            'autoSize': true,
            'titleShow': false,
            'autoScale': false,
            'transitionIn': 'none',
            'transitionOut': 'none',
            'scrolling': 'auto',
            'padding': 0,
            'margin': 0,
            'centerOnScroll': true,
            'height': 'auto',
            'afterShow': function () {
                $(".tvinternal_phone").mask('000000000000', {
                    translation: {
                        '0': {
                            pattern: /[\ \-\0-9]/, optional: true
                        }
                    }
                });
            },
            'helpers': {
                overlay: {
                    locked: false // try changing to true and scrolling around the page
                }
            }
        });


        $('#tv_home_speak').fancybox({
            'wrapCSS': 'tvwrapcss',
            'href': 'webformpopup/index/webform/id/14',
            'type': 'ajax',
            'autoSize': true,
            'titleShow': false,
            'autoScale': false,
            'transitionIn': 'none',
            'transitionOut': 'none',
            'scrolling': 'auto',
            'padding': 0,
            'margin': 0,
            'centerOnScroll': true,
            'height': 'auto',
            'afterShow': function () {
                $(".tvinternal_phone").mask('000000000000', {
                    translation: {
                        '0': {
                            pattern: /[\ \-\0-9]/, optional: true
                        }
                    }
                });
            },
            'helpers': {
                overlay: {
                    locked: false // try changing to true and scrolling around the page
                }
            }
        });

        $('#tv_our_prices').fancybox({
            'wrapCSS': 'tvwrapcss',
            'href': 'webformpopup/index/webform/id/10',
            'type': 'ajax',
            'autoSize': true,
            'titleShow': false,
            'autoScale': false,
            'transitionIn': 'none',
            'transitionOut': 'none',
            'scrolling': 'auto',
            'padding': 0,
            'margin': 0,
            'centerOnScroll': true,
            'height': 'auto',
            'afterShow': function () {
                $(".tvinternal_phone").mask('000000000000', {
                    translation: {
                        '0': {
                            pattern: /[\ \-\0-9]/, optional: true
                        }
                    }
                });
            },
            'helpers': {
                overlay: {
                    locked: false // try changing to true and scrolling around the page
                }
            }
        });

        $('#tv_we_love').fancybox({
            'wrapCSS': 'tvwrapcss',
            'href': 'webformpopup/index/webform/id/11',
            'type': 'ajax',
            'autoSize': true,
            'titleShow': false,
            'autoScale': false,
            'transitionIn': 'none',
            'transitionOut': 'none',
            'scrolling': 'auto',
            'padding': 0,
            'margin': 0,
            'centerOnScroll': true,
            'height': 'auto',
            'afterShow': function () {
                $(".tvinternal_phone").mask('000000000000', {
                    translation: {
                        '0': {
                            pattern: /[\ \-\0-9]/, optional: true
                        }
                    }
                });
            },
            'helpers': {
                overlay: {
                    locked: false // try changing to true and scrolling around the page
                }
            }
        });
    });



</script>