<?php
/*
  Created on : Sep 17, 2015, 2:43:32 PM
  Author     : @Tran Trong Thang
  Email      : trantrongthang1207@gmail.com
  Skype      : trantrongthang1207
 */
echo date('l jS \of F Y h:i:s A');
?>
<div>
    xin chao toi la mot static block
</div>
<?php

function getMostViewedProducts() {
    // number of products to display
    $productCount = 5;

    // store ID
    $storeId = Mage::app()->getStore()->getId();

    // get today and last 30 days time
    $today = time();
    $last = $today - (60 * 60 * 24 * 30);

    $from = date("Y-m-d", $last);
    $to = date("Y-m-d", $today);

    // get most viewed products for last 30 days
    $products = Mage::getResourceModel('reports/product_collection')
            ->addAttributeToSelect('*')
            ->setStoreId($storeId)
            ->addStoreFilter($storeId)
            ->addViewsCount()
            ->addViewsCount($from, $to)
            ->setPageSize($productCount);

    Mage::getSingleton('catalog/product_status')
            ->addVisibleFilterToCollection($products);
    Mage::getSingleton('catalog/product_visibility')
            ->addVisibleInCatalogFilterToCollection($products);

    return $products;
}

$_productCollection = getMostViewedProducts();
$_helper = $this->helper('catalog/output');
?>
<?php foreach ($_productCollection as $_product): ?>
    <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
    <div class="col-md-4">
        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
            <?php /* Based on the native RWD styling, product images are displayed at a max of ~400px wide when viewed on a
              one column page layout with four product columns from a 1280px viewport. For bandwidth reasons,
              we are going to serve a 300px image, as it will look fine at 400px and most of the times, the image
              will be displayed at a smaller size (eg, if two column are being used or viewport is smaller than 1280px).
              This $_imgSize value could even be decreased further, based on the page layout
              (one column, two column, three column) and number of product columns. */ ?>
            <?php $_imgSize = 300; ?>
            <img id="product-collection-image-<?php echo $_product->getId(); ?>"
                 src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->keepFrame(false)->resize($_imgSize); ?>"
                 alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
        </a>
        <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?></a></h2>
    </div>
<?php endforeach ?>

<?php
echo $this->getLayout()->createBlock('ilearn/ilearn')->setTemplate('ilearn/trendingproducts.phtml')->tohtml();
?>