<?php if (Mage::getStoreConfig('prolabels/general/enabled')) : ?>
    <?php $labels = $this->getContentLabels(); ?>
    <?php $_helper = Mage::helper('prolabels') ?>
    <?php $product = $this->getProduct() ?>
    <div class="prolabels-content-wrapper">
        <ul class="tt-wrapper prolabels-content-labels">
            <?php if ($_helper->isMobileMode()) : ?>
                <?php echo $_helper->getMobileLabels($product, 'category') ?>
            <?php endif; ?>
            <?php foreach ($labels as $label) : ?>
                <?php $customUrl = $label['product_custom_url']; ?>
                <?php if ($customUrl) { $labelClick = "openCustomLabelUrl('".$customUrl."');";  } else { $labelClick = ''; }  ?>
                <li>
                    <a class="tt-gplus" href="#" alt="<?php echo $tooltipText; ?>" onclick="<?php echo $labelClick ?>return false;">
                        <img alt="<?php echo $tooltipText; ?>" src="<?php echo Mage::getBaseUrl('media') . "/prolabel/" . $label['category_image'] ?>">
                        <?php if ('' !== $tooltipText=$this->getLabelText($label, 'category')) : ?>
                            <span class="tooltip-label"><?php echo $tooltipText; ?></span>
                        <?php endif; ?>
                    </a>
                </li>
            <?php endforeach; ?>
        </ul>
        <div class="clearer"></div>
    </div>
    <script type="text/javascript">
        function openCustomLabelUrl(url){
            var win = window.open(url, '_blank');
            win.focus();
        }
    </script>
<?php endif; ?>
