<?php
    $_productCollection = $this->getLoadedProductCollection();
    $_helper            = $this->helper('catalog/output');
    $_collectionSize    = $_productCollection->count();
    $_columnCount       = $this->getColumnCount();
?>
<?php if (!$_collectionSize) : return; endif; ?>

<div class="block category-products block-highlight <?php echo $this->getClassName() ?>">
    <div class="block-title"><strong><span><?php echo $this->__($this->getTitle()) ?></span></strong></div>
    <div class="block-content">
        <?php $i=0; foreach ($_productCollection as $_product): ?>
        <?php if ($i++%$_columnCount==0): ?>
        <ul class="products-grid cols-<?php echo $_columnCount ?>">
        <?php endif ?>
            <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
                <a href="<?php echo $this->getProductUrl($_product) ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"
                ><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(80); ?>"
                    srcset="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(80); ?> 1x, <?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(80 * 2); ?> 2x"
                    width="80" height="80"
                    alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"
                /></a>
                <h2 class="product-name"><a href="<?php echo $this->getProductUrl($_product) ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
                <?php echo $this->getPriceHtml($_product, true, $this->getPriceSuffix()) ?>
            </li>
        <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
        </ul>
        <?php endif ?>
        <?php endforeach ?>
        <div class="clearer"></div>
        <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last']);</script>
        <?php if ($this->getPageUrl() && (string)$this->getPageTitle()) : ?>
            <div class="page-link">
                <a href="<?php echo $this->getPageUrl() ?>"><?php echo $this->__((string)$this->getPageTitle()) ?></a>
            </div>
        <?php endif ?>
    </div>
</div>
