<style>
    .soap-notice{
        background: none repeat scroll 0 0 #EAF0EE;
        border: 1px solid #CCCCCC;
        margin-bottom: 10px;
        padding: 11px 0 0 10px;
    }
</style>

<div class="soap-notice">
    <h4><strong style="color:#EA7601;">ROI Tracker v<?php echo $this->getShoppingAnalyticsVersion(); ?> by <a href="http://www.soapmedia.co.uk/" target="_blank">Soap Media</a></strong></h4>
    <p>To keep upto date on this and other modules follow us on <a href="http://twitter.com/soapmedia" target="_blank">twitter</a> or  <a href="http://www.facebook.com/soapmedia" target="_blank">facebook</a></p>
</div>